### ISSUE TITLE
multiple passes?

### ISSUE THREAD

**Issue by jmxo** [bklieger-groq/g1#10]
Hey man, thanks for the great repo! 

What do you think about having multiple passes, depending on the difficulty of the problem? I played around with it with varying degrees of success

fork: https://github.com/jmxo/g1

**Comment by bklieger-groq** [comment]
That is cool! The existing prompt already asks the LLM to do multiple reviews by attempting different methods and considering how it could be incorrect. However, your approach could be helpful for difficult problems as you mentioned. It is a balance between what benefits performance and limiting repetitive tokens.
