### ISSUE TITLE
Can it be used with llama3.1 8B?

### ISSUE THREAD

**Issue by dibu28** [bklieger-groq/g1#12]
Can it be used with llama3.1 8B?
Becouse for the question "How many 'R's are in the word strawberry?" it gives random numbers from 2 to 4.

![image](https://github.com/user-attachments/assets/0c9527eb-1cb2-48e5-a87a-b00e91022521)

I'm using https://github.com/tcsenpai/multi1 repo here with ollama and llama3.1 8B

**Comment by bklieger-groq** [comment]
If you are using mult1, I recommend opening an issue there. Regarding your question, g1 is built powered by Llama-3.1-70b. Smaller models with lower performance abilities like Llama-3.1-8b may give different results.
