### ISSUE TITLE
Example of a failed prompt:

### ISSUE THREAD

**Issue by adamskrodzki** [bklieger-groq/g1#16]
**Write game of snake in javaScript and HTML as a single file**

this results in model getting stuck without outputing anything.

![image](https://github.com/user-attachments/assets/ec8db28a-d4ac-423a-af0d-25d7c6177cbb)

**Comment by bklieger-groq** [comment]
Thank you for sharing. I will investigate. The issue likely lies with the model not generating proper JSON for a response which includes HTML content. I recommend including examples of valid JSON with html content in the response.

**Comment by bklieger-groq** [comment]
This should be fixed once the changes recommended in #18 are completed. Closing this issue accordingly to prevent duplication.
