### ISSUE TITLE
Engaging in secondary development compatible with OpenAI formats

### ISSUE THREAD

**Issue by leezhuuuuu** [bklieger-groq/g1#17]
https://github.com/leezhuuuuu/o1

I have undergone a second development for this project, and it now supports requests in the OpenAI format, supports Streamlit and Cloudflare Worker deployment, and allows for setting a custom base_url and model. Welcome to visit this second development project.

![image](https://github.com/user-attachments/assets/fa560d98-0f57-41c8-940b-5dc9c15dc33c)
![image](https://github.com/user-attachments/assets/27ee0efc-0e23-4a74-ae7d-16a1c367b2d2)

**Comment by bklieger-groq** [comment]
Very cool! Nice work.

**Comment by hihumanzone** [comment]
ohh hey, I also worked on something similar, which you can find here: https://github.com/hihumanzone/g1-simplified. This project utilizes the G1 implementation, but with a modified system prompt and an alternative approach to retrieving the step title and next action. Although it still uses JSON, the explanation can get a bit complex, so feel free to check it out if you're interested. I've modified the system prompt and overall system to encourage the model to think more deeply, maybe a bit of overthinking 🫥, but anyways, here are some screenshots:

![uhm](https://github.com/user-attachments/assets/347250ac-8999-47e8-9b3a-603ca7725c1a)
![yea](https://github.com/user-attachments/assets/d742ea68-7c77-4c72-8ad8-8f63d0d7eedb)

**Comment by hihumanzone** [comment]
ohh, I've also done something similar..
![Screenshot_2024-09-20-22-08-20-59](https://github.com/user-attachments/assets/04daf8ba-157a-4b0b-a2a7-6207cf919216)
