### ISSUE TITLE
Failed to generate step after 3 attempts. Error: local variable 'client' referenced before assignment

### ISSUE THREAD

**Issue by jianlingl** [bklieger-groq/g1#29]
I run according to the readme but get 
**Failed to generate step after 3 attempts. Error: local variable 'client' referenced before assignment**
what does this mean?

**Comment by dashi6174** [comment]
``` g1.py
...
def make_api_call(messages, max_tokens, is_final_answer=False, custom_client=None):
    **global client**

    if custom_client != None:
        client = custom_client
...
```  

add **global client**  can fix this bug

**Comment by jianlingl** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Thanks!And another problem occurred:“Please enable cookies.Sorry, you have been blockedYou are unable to access groq.com"
    How can I fix this problem?Thanks for your time.Jailing li
    
    
    

    

    

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        09/24/2024 16:12
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [bklieger-groq/g1] Failed to generate step after 3 attempts. Error: local variable 'client' referenced before assignment (Issue #29)
        
      
    
  
  
...
def make_api_call(messages, max_tokens, is_final_answer=False, custom_client=None):
    **global client**

    if custom_client != None:
        client = custom_client
...
add global client  can fix this bug

**Comment by bklieger-groq** [comment]
> ```python
> ...
> def make_api_call(messages, max_tokens, is_final_answer=False, custom_client=None):
>     **global client**
> 
>     if custom_client != None:
>         client = custom_client
> ...
> ```
> 
> add **global client** can fix this bug

Thank you. This will be added via #28.

**Comment by bklieger-groq** [comment]
> Thanks!And another problem occurred:“Please enable cookies.Sorry, you have been blockedYou are unable to access groq.com" How can I fix this problem?Thanks for your time.Jailing li

This looks like an issue with your access to Groq. Please reach out to Groq to troubleshoot (https://groq.com/contact/).
