### ISSUE TITLE
Please add hardware requirements in the readme

### ISSUE THREAD

**Issue by iQiexie** [bklieger-groq/g1#5]
Please add hardware requirements in the readme

**Comment by bklieger-groq** [comment]
Hm, the app by default uses a Cloud inference provider called [Groq](https://groq.com/) that offers Llama-3.1-70b. There should not be any significant hardware requirements to call the API. Is there a different requirement you are referring to?

**Comment by iQiexie** [comment]
Oh sorry. For some reason, I thought it's a completely self-hosted project
